/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
    implementation("org.beryx:text-io:3.4.1")
    runtimeOnly("org.slf4j:slf4j-nop:2.0.7")
}

application {
    // Define the main class for the application.
    mainClass = "ch.zhaw.it.pm2.racetrack.TextGameUI"
}
